# for local development
version: '3.7'
services:
  frontend:
    image: hm-client-images
    container_name: hm-client
    build:
      context: .
      target: 'develop-stage'
    ports:
    - '8084:8080'
    volumes:
    - '.:/app'
    command: /bin/sh -c "yarn serve"